version: '3'


services:
  my_parser:
    build:
      context: .
      dockerfile: ./Dockerfile
#    volumes:
#      - ./my_parser:/app
    ports:
      - "${APP_PORT}:5000"
    depends_on:
      - mongo
    env_file:
      - ./.env

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    env_file:
      - ./.env

volumes:
  mongo-data: